name: Daily Test Run

on:
  schedule:
   - cron: "0 0 * * *"
   

jobs:
  test:
  timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set up environment variables
        run: |
          echo "PARABANK_ADDRESS=${{ secrets.PARABANK_ADDRESS }}" >> .env
          echo "PARABANK_CITY=${{ secrets.PARABANK_CITY }}" >> .env
          echo "PARABANK_FIRST_NAME=${{ secrets.PARABANK_FIRST_NAME }}" >> .env
          echo "PARABANK_LAST_NAME=${{ secrets.PARABANK_LAST_NAME }}" >> .env
          echo "PARABANK_PASSWORD=${{ secrets.PARABANK_PASSWORD }}" >> .env
          echo "PARABANK_PHONE=${{ secrets.PARABANK_PHONE }}" >> .env
          echo "PARABANK_SSN=${{ secrets.PARABANK_SSN }}" >> .env
          echo "PARABANK_STATE=${{ secrets.PARABANK_STATE }}" >> .env
          echo "PARABANK_ZIP_CODE=${{ secrets.PARABANK_ZIP_CODE}}" >> .env

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

  send_failure_email:
    runs-on: ubuntu-latest
    needs: test
    if: failure()
    steps:
      - name: Download test artifacts
        uses: actions/download-artifact@v3
        with:
          name: playwright-report
      - name: Send email with failure artifacts
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com 
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Playwright Tests Failed"
          body: "Playwright tests failed in branch ${{ github.ref_name }}. Check failure logs in attachment."
          to: ${{ secrets.EMAIL_USERNAME }}
          from: "GitHub Actions ${{ secrets.EMAIL_USERNAME }}"
          attachments: |
            playwright-report/test-results/test-report.html